package pro.verron.officestamper.test;

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import pro.verron.officestamper.test.utils.OfficeStamperTestBase;

import java.nio.file.Path;
import java.util.Arrays;
import java.util.List;

import static pro.verron.officestamper.preset.OfficeStamperConfigurations.standard;
import static pro.verron.officestamper.test.utils.ResourceUtils.getWordResource;

class GoogleDocsSupportTest extends OfficeStamperTestBase {
    @Test
    @DisplayName("Google Docs support integration test (conditional + repeated paragraphs)")
    void conditionalRepeatedParagraphs_createdByGoogleDocs() {
        var template = getWordResource(Path.of("ConditionalDisplayOfParagraphsGoogleDocs.docx"));
        var expected = """
                == Conditional and repeated paragraph test with document generated by Google Docs
                
                
                
                This block is shown
                
                List items:
                
                // runPr {u=NONE}
                
                item 1
                
                // runPr {u=NONE}
                
                item 2
                
                // section {pgMar={bottom=1134, left=1134, right=1134, top=1134}, pgSz={h=16838, orient=portrait, w=11906}}
                
                """;

        var config = standard();
        var context = new Object() {
            @SuppressWarnings("unused")
            public final boolean showBlock = true;
            @SuppressWarnings("unused")
            public final List<String> items = Arrays.asList("item 1", "item 2");
        };
        testStamper(config, context, template, expected);
    }
}
