= Release Notes
:gh: https://github.com
:os: https://github.com/verronpro/office-stamper
:proj: https://github.com/verronpro/office-stamper/releases/tag

This page provides information about the latest releases of Office-stamper, including new features, bug fixes, and other changes.

== Latest Release

=== {proj}/v2.9.0[v2.9.0]

==== Features

* EXPERIMENTAL: CLI now implements a crude loading of csv, xml, json and property files.

==== Bugfixes

* MAY BREAK: Changed behavior of the processor `replaceWordWith(context)` to be able to handle several test run as notified by {gh}/jonath92[@jonath92] in {os}/issues/585[#585]
** It may break the formatting of the following paragraphs if there was an empty run with formatting instruction inside the comment selection, but I have not been able to reproduce this theoretical issue with both Word, and WPS writer. Do not hesitate to inform me if you encounter the issue.

==== Dependencies

* Upgrade Java version from 21 to 25
* Bump `org.springframework:spring-expression` from `6.2.8` to `6.2.12`
* Bump `org.springframework:spring-context` from `6.2.8` to `6.2.12`

==== Documentation

* Updated all Javadoc to use Markdown style
* Globally added a lot of Javadoc, to improve self-documentation and leverage AI capabilities.
* Add documentation about preprocessors, allowing cleanup of documents before stamping

* Added an .aiignore to improve the vibe coding experience
* Add contributors details to generated documentation site

==== Continuous Integration

* Updated deployment to Maven Central to follow OSSRH process changes.
** Added dependency to plugin `org.sonatype.central:central-publishing-maven-plugin:0.9.0`

* Bump `actions/checkout` from `v4` to `v5`
* Bump `actions/setup-java` from `v4` to `v5`
* Bump `github/codeql-action/analyze` from `v3` to `v4`
* Bump `actions/upload-pages-artifact` from `v3` to `v4`

* Bump `org.apache.maven.plugins:maven-compiler-plugin` from `3.14.0` to `3.14.1`
* Bump `org.apache.maven.plugins:maven-javadoc-plugin` from `3.11.2` to `3.12.0`
* Bump `org.apache.maven.plugins:maven-surefire-plugin` from `3.5.3` to `3.5.4`
* Bump `org.apache.maven.plugins:maven-surefire-report-plugin` from `3.5.3` to `3.5.4`
* Bump `org.jacoco:jacoco-maven-plugin` from `0.8.13` to `0.8.14`

==== Tests

* An improved stringification for paragraphs indentation data (ind elements) as notified by {gh}/jonath92[@jonath92] in {os}/issues/585[#585]
* Added all recent `docx4j` version to test matrix (`11.5.0..11.5.6`)
* Bump `org.pitest:pitest-maven` from `1.20.0` to `1.20.1`
* Bump `org.junit.jupiter:junit-jupiter` from `5.13.3` to `6.0.0`

==== Refactorings

* Improved the comment deletion procedure, to make it less complex and do only one pass through all elements
* Replace the `IndexedRun` concept by the `StandardRun` concept
* MAY BREAK Removed 2 unused public methods from `DocxImageExtractor`

== Previous Releases

For information about previous releases, see the link:https://github.com/verronpro/office-stamper/blob/main/RELEASE_NOTES.adoc[full release notes] on GitHub.

== Upgrading

=== From v2.8.x to v2.9.0

* MAY (unlikely) BREAK some formatting after a replaceWordWith comment.
* Update your dependencies to the latest versions.

=== From v2.7.x to v2.8.0

* No breaking changes.
* Update your dependencies to the latest versions.

=== From v2.6.x to v2.7.0

* If you were using `Paragraph#getComment()`, you'll need to update your code to handle a Collection instead of an Optional.
* Update your dependencies to the latest versions.

=== From v2.5.x to v2.6.x

* No breaking changes.
* Update your dependencies to the latest versions.

=== From v2.4.x to v2.5.x

* No breaking changes.
* Update your dependencies to the latest versions.

== Reporting Issues

If you encounter any issues with a release, report them on the link:https://github.com/verronpro/office-stamper/issues[GitHub Issues] page.

== Next Steps

* Return to the link:index.html[Documentation Home]
* See the link:contributing.html[Contributing] guide if you want to help improve Office-stamper
